version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: veronazavr
      POSTGRES_PASSWORD: password
